### ISSUE TITLE
Partial locking function

### ISSUE THREAD

**Issue by qiekqiek** [Developer-Mike/obsidian-advanced-canvas#120]
现在一锁定就是整个画布被锁定，我希望能只锁定一部分，让样式内容不能调整

**Comment by Developer-Mike** [comment]
Translation: Right now once it's locked it's the whole canvas that's locked, I'd like to be able to lock only a part of it so that the style content can't be adjusted

@qiekqiek For future issues, please use the English lanugage.

This isn't planned, because the mode is called readonly-mode and it should stay readonly 😉 (Similar to #23)

**Comment by qiekqiek** [comment]
OK，i will do it mysefl
