### ISSUE TITLE
[FR] Start Presentation at the selected slide & Disable ESC binding

### ISSUE THREAD

**Issue by trungng2006** [Developer-Mike/obsidian-advanced-canvas#64]
I usually use the page preview/hover editor to trigger a popup to show examples.
The problem is hover editor and Presentation both use `ESC` as the button to end the presentation and destroy the popup.

Hence, I think it would be great if you could add the option to start the presentation at the current/selected slide. 

AND/or remap `ESC` to `CTRL+ESC` to end the presentation.

**Comment by Developer-Mike** [comment]
I'll add a command to end the presentation so you can assign a custom hotkey to it. Additionally, I'll add a setting to disable the "ESC to stop the presentation" keybinding.
The feature to continue at the selected slide is more difficult, and I don't know if I'll add it. The problem is that you can loop back to a slide and then move to a different slide. What should happen in this case? ([Example](https://github.com/Developer-Mike/obsidian-advanced-canvas/blob/main/assets/sample-presentation-complex.gif))

**Comment by trungng2006** [comment]
Thank you for adding the command to end the presentation!!!

 

For the start presentation at the selected slide:

 

I am sorry for not clearly explain the request.

 

My purpose for the continue at selected slide is for when you accidentally ended the presentation.

For example: the presentation flow is 1-2-3-4-5-6

But you accidentally ended the presentation at slide 3.

So you want to start again but at slide 4. You would select slide 4 and trigger the `start presentation`

Then the presentation will continue 4-5-6.

**Comment by Developer-Mike** [comment]
So it looks like the `ESC`-to-exit behavior is forced by the browser engine Obsidian is running on...
In version `2.7.8` I've added an "End Presentation"-Command and a "Continue Presentation"-Command. Those two should make your workflow smoother. If you end a presentation, you can continue where you've left using this command (Or any assigned hotkey).
To fix the `ESC`-key-issue, your best bet is opening an issue in the "Hover Editor"-Plugin and ask them for e.g. a command to close their popup. Sorry for creating some false hopes for the `ESC`-key fix 😥.

**Comment by trungng2006** [comment]
No need to apologize.
I appreciate that you spent time and effort to help solve my problem.
Thank you so much!!!
