### ISSUE TITLE
[BUG] cssclasses don't work

### ISSUE THREAD

**Issue by CatCodeMe** [Developer-Mike/obsidian-advanced-canvas#79]
Hello Mike, this is my problem.
# env
- plugin version 3.0.3
- these css-snippetes is downloaded from https://github.com/HandaArchitect/obsidian-banner-snippet/releases

# issue
I have added a css-snippet , it works when I add `cssclasses：banner` , like this

<img width="427" alt="image" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/11496772/f9009b49-f0af-4c22-8d1f-c52c8b697a7f">

rendered like this

<img width="397" alt="image" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/11496772/842b7f1d-6c08-4a43-94e3-c6f19b7700c1">

Now, I want to use plugin's `cssclasses` to reach this goal, but it don't work, don't have any changes.
- I remove these cssclasses `banner` from card content. 
<img width="556" alt="image" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/11496772/938141aa-4bc7-45a7-87af-cc08fca8811b">
 
so, is it a bug ? And If I want to add multiple cssclasses, use `banner, banner-fade` ?

**Comment by Developer-Mike** [comment]
This issue is caused by the snippet which isn't made for canvas. Advanced Canvas adds the class to the canvas-wrapper element rather than to each node. To make your CSS snippet compatible, you need to add a space before every `.markdown-preview-view`. If you adjust this, any children (in this case the nodes) also get affected by the style.

If you want to add multiple classes you can separate them using spaces.
