### ISSUE TITLE
Opended portal layer over other nodes

### ISSUE THREAD

**Issue by emtothed** [Developer-Mike/obsidian-advanced-canvas#81]
Hey there

currently when you open a portal it goes under the existing nodes in the canvas it would be great if the opened portal come before other layers (or having the option and choose in the setting) and cover other nodes so that you can clearly see the portal 

thank you so much

Update : I noticed the portal's nodes are already on the top, but as you can see in the picture the portal nodes clash with other nodes when you put the closed portal node in a tight place near other nodes, can we have some kind of blurred background for portals in the setting for preventing this kind of situation but also somehow maintaining the integrity of the portal with the underlying canvas? (or any other solution you feel fits the situation)

![portal](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/110118604/fe5ae4a0-9672-482f-ba44-93fa1874079f)

**Comment by Developer-Mike** [comment]
Thank you for your suggestion. Unfortunately, this won't be added. 
The first reason is that the portals shouldn't be a separate unit in your canvas. The "teleported" nodes should be treated like other nodes (You can e.g. make connections to them like a normal node). If you want to restrict them to a confined space, consider not opening the portal at all.
The second, less relevant reason is the rather difficult implementation. The problem is that the "teleported" edges, for example, are on the same layer as the other edges. Because of this missing separation, blurring or hiding the content isn't an easy task.

**Comment by emtothed** [comment]
I totally get you, after a little bit of working with it I found out what you were looking for when you were implementing it. I was trying to have a home page canvas that contains a complete map of my whole vault and some portal nodes are getting placed in the middle of other nodes, I'll try to manage the situation in some other way. 

Really appreciate your time and support.
