### ISSUE TITLE
[FR] Bring back the old style menu

### ISSUE THREAD

**Issue by SpaciousTech** [Developer-Mike/obsidian-advanced-canvas#88]
Is it possible to make the node popups menu to show all buttons of the shapes, text, and border directly? Currently, I have to click on "Style" then have to choose to between three other menus, "text", "shapes" or "border" then another menu.

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/55485515/5df9cb26-f3e9-4e9f-8289-21e06208e77d)

I saw an old video (3 months) showing the plugin with a much less compact menu and only showing the shapes without the cluster of text:

![image](https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/55485515/ba6f70f9-41e4-4380-b2f9-3747059fbd0a)

Sorry if that was brought up before.

**Comment by Developer-Mike** [comment]
This change was made because the buttons above a node were above the likable amount. I can understand your desire to switch back to the old layout, but this is currently not possible.

I'm curious about other people's opinions about this change. Let's vote 👍🏻/👎🏻 on this comment if you like the NEW, nested menu style.

**Comment by SpaciousTech** [comment]
I see, thanks for clarifying. It would be nice to have the option to choose between the old and new layout.

**Comment by Developer-Mike** [comment]
The old style got re-added in version `3.1.0`
